# -*- coding: utf-8 -*-
"""Seminar10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NTVmnJaCXAGzWUw3ToW4m0Dm_WlmTNPl

## Задача №63
1. Изобразите отношение households к population с помощью точечного графика
2. Визуализировать longitude по отношения к median_house_value, используя линейный график
3. Представить гистограмму по housing_median_age
4. Изобразить гистограмму по median_house_value с оттенком housing_median_age
"""


import pandas as pd
import seaborn as sns
df = pd.read_csv('sample_data/california_housing_test.csv')
df.head()

# Изобразите отношение households к population с помощью точечного графика
sns.scatterplot(data = df, x = 'households', y = 'population');

# Визуализировать longitude по отношения к median_house_value, используя линейный график
sns.relplot(x='longitude', y='median_house_value', kind='line', data=df);

# 3 Представить гистограмму по housing_median_age
sns.histplot(data=df, x='housing_median_age');

# Изобразить гистограмму по median_house_value с оттенком housing_median_age
sns.displot(x='median_house_value', hue='housing_median_age', data = df);

"""# Задача 65: Написать EDA для датасета про пингвинов. Необходимо: 
● Использовать 2-3 точечных графика 

● Применить доп измерение в точечных графиках, используя аргументы hue, size, stile 

● Использовать PairGrid с типом графика на ваш выбор 

● Изобразить Heatmap 

● Использовать 2-3 гистограммы 

Чтобы подключить датасет с пингвинами, воспользуйтесь данным скриптом: 
penguins = sns.load_dataset("penguins") penguins.head()

"""

penguins = sns.load_dataset("penguins")
penguins.head()

sns.scatterplot(data = penguins, x='bill_length_mm', y='bill_depth_mm', hue='sex', size=5);

sns.scatterplot(data = penguins, x='body_mass_g', y='flipper_length_mm', hue='sex', size=6);

sns.scatterplot(data = penguins, x='bill_depth_mm', y='bill_length_mm', hue='body_mass_g', size=4);

sns.scatterplot(data = penguins, x='bill_length_mm', y='bill_depth_mm', hue='sex', size=5)
sns.scatterplot(data = penguins, x='body_mass_g', y='flipper_length_mm', hue='sex', size=6)
sns.scatterplot(data = penguins, x='bill_depth_mm', y='bill_length_mm', hue='body_mass_g', size=4);

# Использовать PairGrid с типом графика на ваш выбор
lst = ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g', 'sex']
g = sns.PairGrid(penguins[lst]) # Создали методом пустые графики
g.map(sns.scatterplot);

sns.histplot(data=penguins, x='bill_depth_mm');

sns.histplot(data=penguins, x='bill_length_mm');

sns.histplot(data=penguins, x='flipper_length_mm');

# Изобразить Heatmap
# import numpy
# corr_matrix = df.corr()
# sns.heatmap(corr_matrix, linewidths = 0.5, cmap='coolwarm', annot=True);

"""# Задача 67: 
Создать новый столбец в таблице с пингвинами, который будет отвечать за показатель длины клюва пингвина. high - длинный(от 42) middle - средний(от 35 до 42) low - маленький(до 35)
Чтобы подключить датасет с пингвинами, воспользуйтесь данным скриптом: 
penguins = sns.load_dataset("penguins") penguins.head()

"""

# Создать новый столбец в таблице с пингвинами, который будет отвечать за показатель длины клюва пингвина. high - высокий(от 42), middle - средний(от 35 до 42), low - низкий(до 35).
# df.loc[df['bill_length_mm'] >= 42, 'height_group'] = 'high'
# df.loc[(df['bill_length_mm'] >= 35) & (df['bill_length_mm'] < 42), 'height_group'] = 'middle'
# df.loc[df['bill_length_mm'] < 35, 'height_group'] = 'low'

"""#Задача 69: 
Изобразить гистограмму по flipper_length_mm с оттенком height_group. Сделать анализ
"""

# Изобразить гистограмму по flipper_length_mm с оттенком height_group. Сделать анализ
# sns.displot(df, x="flipper_length_mm", hue="height_group")